name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@2.0.7 #Github Action version
        with:
          project_name: KHTestGitHubAction
          cx_tenant: Cx_emea_ses_canary_kishor_hasurkar_canar
          base_uri: https://deu.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          branch: master
